Add DID rotation
decentralized-identity/didcomm.org pull request #49
Opened 2022-07-09 19:19 UTC by rodolfomiranda

Adding DID Rotation section

2022-07-27 15:58 UTC, 2byrds requested changes
Great stuff!  Learned a ton.  Typo fixes requested.

2022-07-27 15:58 UTC, 2byrds commented on site/content/book/v2/didrotation.md
> +Example code showin a DID Rotation after an Out of Band message can be found in the section [Starting, using and ending a DIDComm connection](startConnection) from this Guidebook.
(typo fix) Example code showing

2022-07-27 15:58 UTC, 2byrds commented on site/content/book/v2/didrotation.md
> +Since DIDComm is asynchronous in nature, messages can arrive in different order. Sender and receiver should be care of:
(typo fix) Sender and receiver should take care to:

2022-07-27 15:58 UTC, 2byrds commented on site/content/book/v2/didrotation.md
> +- Receiver: messages received from the old DID but after the message that performs the DID rotation must be discarded to reduce the risk of potential compromised keys.
(typo fix) risk of potentially compromised keys.

2022-07-27 20:07 UTC, TelegramSam commented on site/content/book/v2/didrotation.md
> +[DIDComm Messaging](https://identity.foundation/didcomm-messaging/spec/) relies on the [DIDs](https://www.w3.org/TR/did-core/), and associated [DID Documents](https://www.w3.org/TR/did-core/#dfn-did-
This is a minor nit, but key rotations can and should happen even if they are not compromised. Adding just a bit to acknowledge that will prevent it from detracting from the larger work you've contributed.

2022-07-27 20:13 UTC, TelegramSam commented on site/content/book/v2/didrotation.md
> +
Another reason is needing or wanting to move from one DID method to another.

2022-07-27 20:16 UTC, TelegramSam commented
I love this! thanks for your work. It might be worth a mention that the party doing the rotation should continue to send the rotation header until they receive a message from the other party using the new DID. This allows for continuity even if one party is offline or not processing messages for a bit.

2022-07-31 20:48 UTC, rodolfomiranda commented
In last commit I corrected the typos and added @TelegramSam suggestions.

2022-08-10 10:18 UTC, dhh1128 approved these changes

2022-08-10 10:18 UTC, merged